# Generated by Django 4.2.19 on 2025-03-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study_example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "deptno",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("dname", models.CharField(max_length=14)),
                ("loc", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryGrade",
            fields=[
                (
                    "grade",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("losal", models.PositiveIntegerField()),
                ("hisal", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "empno",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("ename", models.CharField(max_length=10)),
                ("job", models.CharField(max_length=9)),
                ("hiredate", models.DateField()),
                ("sal", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "comm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "deptno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study_example.department",
                    ),
                ),
                (
                    "mgr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="study_example.employee",
                    ),
                ),
            ],
        ),
    ]
